rails02-work/config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :works
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "works#index"
end

rails02-work/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

rails02-work/app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

rails02-work/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :works

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

rails02-work/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_paper_trail
end

rails02-work/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

rails02-work/app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

rails02-work/app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

rails02-work/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

rails02-work/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: %i[ show edit update destroy ]

  # GET /works
  def index
    @works = Work.all
  end

  # GET /works/1
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
    @work.user = Current.user if Current.user
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  def create
    @work = Work.new(work_params)

    if @work.save
      redirect_to @work, notice: "Work was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /works/1
  def update
    if @work.update(work_params)
      redirect_to @work, notice: "Work was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /works/1
  def destroy
    @work.destroy!
    redirect_to works_path, notice: "Work was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.expect(work: [ :user_id, :work_on, :start_at, :end_at, :location, :body, :approved ])
    end
end

rails02-work/app/helpers/works_helper.rb
module WorksHelper
end

rails02-work/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails02 Work" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails02-work/app/views/works/_form.html.erb
<%= form_with(model: work) do |form| %>
  <% if work.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</p>

      <ul>
        <% work.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id %>
    <%= form.number_field :user_id, class: "form-control" %>
  </div>

  <div>
    <%= form.label :work_on %>
    <%= form.date_field :work_on, class: "form-control" %>
  </div>

  <div>
    <%= form.label :start_at %>
    <%= form.datetime_field :start_at, class: "form-control" %>
  </div>

  <div>
    <%= form.label :end_at %>
    <%= form.datetime_field :end_at, class: "form-control" %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.textarea :body, class: "form-control" %>
  </div>

  <div>
    <%= form.label :approved %>
    <%= form.checkbox :approved, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

rails02-work/app/views/works/_work.html.erb
<div id="<%= dom_id work %>">
  <p>
    <strong>User:</strong>
    <%= work.user_id %>
  </p>

  <p>
    <strong>Work on:</strong>
    <%= work.work_on %>
  </p>

  <p>
    <strong>Start at:</strong>
    <%= work.start_at %>
  </p>

  <p>
    <strong>End at:</strong>
    <%= work.end_at %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= work.location %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= work.body %>
  </p>

  <p>
    <strong>Approved:</strong>
    <%= work.approved %>
  </p>

</div>

rails02-work/app/views/works/edit.html.erb
<% content_for :title, "Editing work" %>

<h1>Editing work</h1>

<%= render "form", work: @work %>

<br>

<div>
  <%= link_to "Show this work", @work %> |
  <%= link_to "Back to works", works_path %>
</div>

rails02-work/app/views/works/index.html.erb
<% content_for :title, "Works" %>

<h1>Works</h1>

<table id="works" class="table">
  <% @works.each do |work| %>
    <tr>
      <td>
        <%= render work %>
      </td>
      <td>
        <%= link_to "Show this work", work %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "New work", new_work_path, class: "btn btn-primary" %>

rails02-work/app/views/works/new.html.erb
<% content_for :title, "New work" %>

<h1>New work</h1>

<%= render "form", work: @work %>

<br>

<div>
  <%= link_to "Back to works", works_path %>
</div>

rails02-work/app/views/works/show.html.erb
<%= render @work %>

<div>
  <%= link_to "Edit this work", edit_work_path(@work) %> |
  <%= link_to "Back to works", works_path %>

  <%= button_to "Destroy this work", @work, method: :delete %>
</div>