rails03-vote/config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :votes
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#root"
end

rails03-vote/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails03-vote/app/models/event.rb
class Event < ApplicationRecord
    has_many :votes, dependent: :destroy
    belongs_to :user, optional: true

    validates :title, presence: true
    validates :schedules, presence: true

    has_rich_text :description

    def schedules_array
        schedules.split(',').map(&:strip)
    end

    def count_votes
        l = schedules_array.length
        o = [0] * l
        x = [0] * l
        votes.each do |vote|
            vote.answers_array.each_with_index do |answer, index|
                if answer == 'o'
                    o[index] += 1
                elsif answer == 'x'
                    x[index] += 1
                end
            end
        end
        {o: o, x: x}
    end

    def indexes_of_top_schedules
        counts = count_votes
        o = counts[:o]
        max_count = o.max
        indexes = []
        return indexes if max_count == 0
        o.each_with_index do |count, index|
            indexes << index if count == max_count
        end
        if indexes.length > 1
            x = counts[:x]
            min_count = x.each_with_index.select { |v, i| indexes.include?(i) }.map { |count, index| count }.min
            indexes = []
            x.each_with_index do |count, index|
                indexes << index if count == min_count
            end
        end
        indexes
    end

    def token
        Digest::SHA1.hexdigest("#{id}-#{created_at}").slice(0, 8)
    end
end

rails03-vote/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

rails03-vote/app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :event

  validates :name, presence: true
  validates :answers, presence: true

  def answers_array
    answers.split(",").map(&:strip)
  end

  def update_answers(params)
    raise "params can not be nil" unless params
    raise "can not find event for updating answers" unless event
    answers_array = [nil] * event.schedules_array.count
    answers_array.count.times do |i|
      answers_array[i] = params["answers_#{i}"]
    end
    self.answers = answers_array.join(",")
  end
end

rails03-vote/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: %i[ root new create show ]

  # GET /events or /events.json
  def index
    @events = Event.all.order("id desc")
  end

  # GET /events/1 or /events/1.json
  def show
    unless authenticated?
      if params[:token] != @event.token
        redirect_to root_path(@event), notice: "イベントにアクセスするにはログインするかトークンが必要です。"
        return
      end
    end
    @votes = @event.votes.order(:id)
    @selected_rows = @event.indexes_of_top_schedules
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = Current.session&.user&.id || 1 # If user is not logged in, set to 1 (admin)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_path(@event,token:@event.token), notice: "イベントを新規作成しました。" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "イベントを更新しました。" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def root
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.expect(event: [ :title, :schedules, :user_id, :description ])
    end
end

rails03-vote/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: %i[ new create show ]

  # GET /votes or /votes.json
  def index
    event_id = params[:event_id].to_i
    if event_id > 0
      @event = Event.find(event_id)
      @votes = Vote.where(event_id: event_id).order(:id)
    else
      @votes = Vote.order(:id)
    end
  end

  # GET /votes/1 or /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes or /votes.json
  def create
    @vote = Vote.new(vote_params)
    @vote.update_answers(params)
    respond_to do |format|
      if @vote.save
        format.html { redirect_to event_path(@vote.event, token: @vote.event.token), notice: "予定を登録しました！" }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1 or /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: "Vote was successfully updated." }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1 or /votes/1.json
  def destroy
    event_id = @vote.event_id
    @vote.destroy!

    respond_to do |format|
      format.html { redirect_to votes_path(event_id: event_id), status: :see_other, notice: "回答を削除しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def vote_params
      params.expect(vote: [ :event_id, :name, :comment ]) # answers will be set in Vote.update_answers
    end
end

rails03-vote/app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      next if message.blank?

      t = "light"
      t = "info" if type == "notice"
      t = "danger" if type == "alert"

      flash_messages << content_tag(:div, message.html_safe, class: "alert alert-#{t}")
    end
    flash_messages.join("\n").html_safe
  end
end

rails03-vote/app/helpers/events_helper.rb
module EventsHelper
  def sample_schedules
    t = Time.now
    dates = []
    3.times do
      t += 1.day + 1.hour
      dates += [t.strftime("%m/%d %H:00")]
    end
    dates.join(", ")
  end
end

rails03-vote/app/helpers/votes_helper.rb
module VotesHelper
end

rails03-vote/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

rails03-vote/app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <h1><%= event.title %></h1>

  <p><%= event.description %></p>
</div>

rails03-vote/app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(event.errors.count, "つ") %>のエラーがあります:</p>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :schedules %>
    <%= form.text_field :schedules, placeholder: sample_schedules, class: "form-control" %>
    <small>コンマ(,)区切りで候補日を2つ以上記入します。 例: 4/30 14:00, 5/1 15:00</small>
  </div>

  <div class="mt-3">
    <%= form.submit "イベントを作成する", class: "btn btn-primary" %>
  </div>
<% end %>

rails03-vote/app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>イベントの編集</h1>

<%= render "form", event: @event %>

<div class="alert alert-info mt-3">
  既に回答がついている場合、候補日時は編集せず、新規にイベントを作成してください。
</div>

<div>
  <%= link_to "表示", @event, class: "btn btn-light" %>
  <%= link_to "一覧", events_path, class: "btn btn-light" %>
</div>

rails03-vote/app/views/events/index.html.erb
<% content_for :title, "イベント一覧" %>

<h1>イベント一覧</h1>

<%= link_to "新しいイベント", new_event_path, class: "btn btn-primary" %>

<table id="events" class="table">
  <% @events.each do |event| %>
    <tr>
      <td>
        <%= link_to event.title, event_path(event, token: event.token) %>
      </td>
      <td>
        <small>
        <%= strip_tags(event.description.to_s).truncate(80) %>
        </small>
      </td>
      <td class="text-muted text-end">
        <small>
        <%= event.votes.count %><br>
        <%= event.created_at.strftime("%Y/%m/%d %H:%M") %></small>
      </td>
    </tr>
  <% end %>
</table>

rails03-vote/app/views/events/new.html.erb
<% content_for :title, "新しいイベント" %>

<div class="row">
  <div class="col-md-6">

<h1>新しいイベント</h1>

<%= render "form", event: @event %>

<br>

<% if authenticated? %>
<div class="for-admin">
  <%= link_to "一覧", events_path, class: "btn btn-light" %>
</div>
<% end %>

</div>

<div class="col-md-6">
  <p>イベントを作成するには、フォームに必要な情報を入力してください。作成後のURLを共有することで、他の方に回答を追加してもらうことができるようになります。</p>
  <p>イベントの詳細は、後で編集することもでき…るようにしたいのですが、現在、<a href="https://x.com/YoseiIto" target="_blank">管理者</a>のみが操作可能です。
  修正したい場合は、新たに作り直すか、個別にご連絡ください（回答がついた後は、管理者でも候補日時の編集はできません）。</p>
</div>
</div>

rails03-vote/app/views/events/root.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3 bg-light p-3 mb-3 rounded">
        <p>イベント日程調整ツール。rev1</p>
        <p><a href="https://lmlab.net/books/2501_rails">Dive into Ruby on Rails 2025</a>
        という書籍で構築する(予定の)サンプルアプリケーションです。誰でも（ログインなしで）イベントの候補日に対する
        参加可否の投票ができるフォームを作成することができます。<br>
        </p>
    </div>
</div>

<div class="text-center">
    <%= link_to '新しいイベントを作成する', new_event_path, class: "btn btn-lg btn-success" %>
</div>

rails03-vote/app/views/events/show.html.erb
<% content_for :title, @event.title+"の日程調整" %>

<%= render @event %>

<table class="table">
  <tr>
    <th>予定</th>
    <% @votes.each do |vote| %>
      <th><%= vote.name %></th>
    <% end %>
  </tr>
  <% @event.schedules_array.each_with_index do |schedule,i| %>
    <tr class="<%= 'table-success' if @selected_rows.include? i %>">
      <th><%= schedule %></th>
      <% @votes.each do |vote| %>
        <td><%= vote.answers_array[i] %></td>
      <% end %>  
    </tr>
  <% end %>
  <tr>
    <th></th>
    <% @votes.each do |vote| %>
      <td class="text-muted small"><%= vote.comment %></td>
    <% end %>  
  </tr>
</table>

<div class="row">
  <div class="col-md-6">    
    <p>予定を教えてください！</p>
    <% v = Vote.new; v.event = @event %>
    <%= render 'votes/form', vote: v, show_event_title: false %>
  </div>
  <div class="col-md-6">
    <p>他の人にこのイベントのURLを共有して回答を追加してもらうことができます。<br>※不特定の人が見える場所(SNSのポストなど)に貼り付けないように注意してください！</p>
    <%= link_to event_url(@event, token: @event.token), event_url(@event, token: @event.token), class: "form-control" %>
  </div>
</div>

<% if authenticated? %>
<div class="mt-5 for-admin">
  <%= link_to "編集", edit_event_path(@event), class: "btn btn-light" %>
  <%= link_to "一覧", events_path, class: "btn btn-light" %>
  <%= link_to "回答一覧", votes_path(event_id: @event.id), class: "btn btn-light" %>

  <%= button_to "削除する", @event, method: :delete, class: "btn btn-danger mt-2" %>
</div>
<% end %>

rails03-vote/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

rails03-vote/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Vote" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light main">
      <div class="container main">
      <a class="navbar-brand" href="/">
        <%= image_tag "header-logo.png", alt: "LmLab" %>
        日程調整 β
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
          </ul>
          <span class="navbar-text">
          <% if authenticated? %>
            <%= link_to "<i class='bi bi-house'></i>".html_safe, events_path, class: "btn btn-sm btn-outline-secondary ms-2", title: Current.session.user.email_address %>
            <%= link_to "Sign out", session_path, data: {turbo_method: :delete}, class: "btn btn-sm btn-outline-secondary ms-2" %>
          <% else %>
            <%= link_to "<i class='bi bi-lock'></i>".html_safe, new_session_path, class: "btn btn-sm btn-outline-secondary" %>
          <% end %>
          </span>
        </div>
      </div>
    </nav>
    </header>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <footer class="text-center my-5">
      <%= link_to 'lmlab.net', 'https://lmlab.net', target: '_blank', class: 'text-muted' %>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  </body>
</html>

rails03-vote/app/views/votes/_form.html.erb
<%= form_with(model: vote) do |form| %>
  <% if vote.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(vote.errors.count, "つ") %>のエラー:</p>

      <ul>
        <% vote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :event_id %>
  <% if show_event_title %>
    <div>
      <%= form.label :event_id, "イベント" %>
      <input type="text" value="<%= vote.event.title %>" class="form-control" readonly>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name, "あなたの名前" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :answers_array, "あなたの予定" %>
    <table class="table">
    <% vote.event.schedules_array.each_with_index do |schedule,i| %>
      <tr>
      <th><%= schedule %></th>
      <% ["o", "x", "?"].each do |answer| %>
        <td>
          <%= radio_button_tag "answers_#{i}", answer, class: "form-check-input" %>
          <%= form.label nil, answer, for: "answers_#{i}_#{answer}" %>
        </td>
      <% end %>
      </tr>
    <% end %>  
    </table>
  </div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_field :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "回答を追加する", class: "btn btn-lg btn-primary mt-2" %>
  </div>
<% end %>

rails03-vote/app/views/votes/_vote.html.erb
<div id="<%= dom_id vote %>">
  <p>
    <strong>Event:</strong>
    <%= vote.event_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= vote.name %>
  </p>

  <p>
    <strong>Answers:</strong>
    <%= vote.answers %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= vote.comment %>
  </p>

</div>

rails03-vote/app/views/votes/edit.html.erb
<% content_for :title, "Editing vote" %>

<h1>回答</h1>

<%= render "form", vote: @vote %>

<br>

<% if authenticated? %>
  <div class="for-admin">
  <%= link_to "Show this vote", @vote %> |
  <%= link_to "Back to votes", votes_path %>
</div>
<% end %>

rails03-vote/app/views/votes/index.html.erb
<% content_for :title, "回答" %>

<h1><%= @event&.title %>への回答</h1>

<table id="votes" class="table">
  <% @votes.each do |vote| %>
    <tr>
      <td>
        <%= link_to vote.name, vote %>
      </td>
      <td>
        <%= vote.answers %>
      </td>
      <td>
        <%= vote.comment %>
      </td>
    </tr>
  <% end %>
</table>

<% if @event %>
<%= link_to "戻る", event_path(@event), class: "btn btn-light" %>
<% end %>

rails03-vote/app/views/votes/new.html.erb
<% content_for :title, "新しい回答" %>

<h1>新しい回答</h1>

<%= render "form", vote: @vote, show_event_title: true %>

<br>

<%= link_to "イベントに戻る", event_path(@vote.event, token: @vote.event.token), class: "btn btn-light" %>

<% if authenticated? %>
<div class="for-admin mt-5">
  <%= link_to "一覧に戻る", votes_path %>
</div>
<% end %>

rails03-vote/app/views/votes/show.html.erb
<%= render @vote %>

<div>
  <%= link_to "Edit this vote", edit_vote_path(@vote), class: "btn btn-light" %>
  <%= link_to "Back to votes", votes_path, class: "btn btn-light" %>

  <%= button_to "Destroy this vote", @vote, method: :delete, class: "btn btn-danger mt-2" %>
</div>