rails01-inquiry/config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "inquiries#new"
end

rails01-inquiry/app/models/inquiry.rb
class Inquiry < ApplicationRecord
  has_many_attached :images
end

rails01-inquiry/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      pw = Rails.application.credentials.basis_auth_password
      if (username == "kanri" && password == pw)
        session[:user] = username
      end
    end
  end
end

rails01-inquiry/app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: %i[ show edit update destroy ]
  before_action :authenticate, except: [:show, :new, :create]

  # GET /inquiries
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  def create
    @inquiry = Inquiry.new(inquiry_params)

    if @inquiry.save
      InquiriesMailer.sent(to: @inquiry.email).deliver_later
      InquiriesMailer.received.deliver_later
      redirect_to @inquiry, notice: "Inquiry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /inquiries/1
  def update
    if @inquiry.update(inquiry_params)
      redirect_to @inquiry, notice: "Inquiry was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /inquiries/1
  def destroy
    @inquiry.destroy!
    redirect_to inquiries_path, notice: "Inquiry was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def inquiry_params
      params.expect(inquiry: [ :name, :email, :purpose, :body, images:[]])
    end
end

rails01-inquiry/app/helpers/inquiries_helper.rb
module InquiriesHelper
end

rails01-inquiry/app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry) do |form| %>
  <% if inquiry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
        <% inquiry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :purpose %>
    <%= form.number_field :purpose, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.textarea :body, class: "form-control" %>
  </div>

  <div class="form-field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

rails01-inquiry/app/views/inquiries/_inquiry.html.erb
<div id="<%= dom_id inquiry %>">
  <p>
    <strong>Name:</strong>
    <%= inquiry.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= inquiry.email %>
  </p>

  <p>
    <strong>Purpose:</strong>
    <%= inquiry.purpose %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= inquiry.body %>
  </p>

  <% if inquiry.images.attached? %>
  <p>
  <% inquiry.images.each do |i| %>
    <%= image_tag i %>
  <% end %>
  </p>
  <% end %>
</div>

rails01-inquiry/app/views/inquiries/edit.html.erb
<% content_for :title, "Editing inquiry" %>

<h1>Editing inquiry</h1>

<%= render "form", inquiry: @inquiry %>

<br>

<div>
  <%= link_to "Show this inquiry", @inquiry %> |
  <%= link_to "Back to inquiries", inquiries_path %>
</div>

rails01-inquiry/app/views/inquiries/index.html.erb
<% content_for :title, "Inquiries" %>

<h1>Inquiries</h1>

<div id="inquiries">
  <% @inquiries.each do |inquiry| %>
    <div class="card mb-3">
      <div class="card-body">
      <%= render inquiry %>
      <p class="card-text">
        <%= link_to "Show this inquiry", inquiry, class: "btn btn-light" %>
      </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New inquiry", new_inquiry_path, class: "btn btn-primary" %>

rails01-inquiry/app/views/inquiries/new.html.erb
<% content_for :title, "New inquiry" %>

<div class="row">
  <div class="offset-md-3 col-md-6">
<h1>New inquiry</h1>

<%= render "form", inquiry: @inquiry %>

<% if session[:user] == "admin" %>
<br>

<div>
  <%= link_to "Back to inquiries", inquiries_path %>
</div>
<% end %>
  </div>
</div>

rails01-inquiry/app/views/inquiries/show.html.erb
<% if session[:user] == "kanri" %>
<%= render @inquiry %>

<div>
  <%= link_to "Edit this inquiry", edit_inquiry_path(@inquiry) %> |
  <%= link_to "Back to inquiries", inquiries_path %>

  <%= button_to "Destroy this inquiry", @inquiry, method: :delete %>
</div>
<% else %>
  <p>Thank you for the inquiry!</p>
<% end %>

rails01-inquiry/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails01 Inquiry" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <div id="notice" class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div id="alert" class="alert alert-warning"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>